const sampleData = {
    "latitude": 41.4366485,
    "longitude": 2.1726443,
    "timezone": "Europe/Madrid",
    "currently": {
        "time": 1566067188,
        "summary": "Partly Cloudy",
        "icon": "partly-cloudy-day",
        "precipIntensity": 0,
        "precipProbability": 0,
        "temperature": 27.27,
        "apparentTemperature": 29.13,
        "dewPoint": 20.86,
        "humidity": 0.68,
        "pressure": 1014.07,
        "windSpeed": 11.66,
        "windGust": 18.32,
        "windBearing": 193,
        "cloudCover": 0.24,
        "uvIndex": 0,
        "visibility": 10.977,
        "ozone": 291.2
    },
    "hourly": {
        "summary": "Humid and partly cloudy throughout the day.",
        "icon": "partly-cloudy-day",
        "data": [
            {
                "time": 1566064800,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 27.97,
                "apparentTemperature": 30,
                "dewPoint": 20.83,
                "humidity": 0.65,
                "pressure": 1013.9,
                "windSpeed": 13.93,
                "windGust": 20.02,
                "windBearing": 198,
                "cloudCover": 0.22,
                "uvIndex": 0,
                "visibility": 10.003,
                "ozone": 290.6
            },
            {
                "time": 1566068400,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 26.91,
                "apparentTemperature": 28.67,
                "dewPoint": 20.88,
                "humidity": 0.7,
                "pressure": 1014.16,
                "windSpeed": 10.51,
                "windGust": 17.46,
                "windBearing": 189,
                "cloudCover": 0.25,
                "uvIndex": 0,
                "visibility": 11.471,
                "ozone": 291.5
            },
            {
                "time": 1566072000,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 25.88,
                "apparentTemperature": 26.45,
                "dewPoint": 20.78,
                "humidity": 0.73,
                "pressure": 1014.46,
                "windSpeed": 6.24,
                "windGust": 13.99,
                "windBearing": 216,
                "cloudCover": 0.2,
                "uvIndex": 0,
                "visibility": 16.093,
                "ozone": 292.7
            },
            {
                "time": 1566075600,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 25.11,
                "apparentTemperature": 25.66,
                "dewPoint": 20.55,
                "humidity": 0.76,
                "pressure": 1014.65,
                "windSpeed": 4.16,
                "windGust": 10.89,
                "windBearing": 262,
                "cloudCover": 0.17,
                "uvIndex": 0,
                "visibility": 16.093,
                "ozone": 293.6
            },
            {
                "time": 1566079200,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 24.58,
                "apparentTemperature": 25.12,
                "dewPoint": 20.42,
                "humidity": 0.78,
                "pressure": 1014.62,
                "windSpeed": 4.26,
                "windGust": 8.24,
                "windBearing": 288,
                "cloudCover": 0.15,
                "uvIndex": 0,
                "visibility": 16.093,
                "ozone": 293.8
            },
            {
                "time": 1566082800,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 23.96,
                "apparentTemperature": 24.48,
                "dewPoint": 20.09,
                "humidity": 0.79,
                "pressure": 1014.81,
                "windSpeed": 4.76,
                "windGust": 6.01,
                "windBearing": 324,
                "cloudCover": 0.2,
                "uvIndex": 0,
                "visibility": 16.093,
                "ozone": 293.5
            },
            {
                "time": 1566086400,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 23.44,
                "apparentTemperature": 23.92,
                "dewPoint": 19.77,
                "humidity": 0.8,
                "pressure": 1014.63,
                "windSpeed": 5.17,
                "windGust": 5.17,
                "windBearing": 328,
                "cloudCover": 0.22,
                "uvIndex": 0,
                "visibility": 16.093,
                "ozone": 293.5
            },
            {
                "time": 1566090000,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 22.89,
                "apparentTemperature": 23.35,
                "dewPoint": 19.44,
                "humidity": 0.81,
                "pressure": 1014.32,
                "windSpeed": 5.23,
                "windGust": 5.23,
                "windBearing": 328,
                "cloudCover": 0.23,
                "uvIndex": 0,
                "visibility": 16.093,
                "ozone": 293.9
            },
            {
                "time": 1566093600,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 22.32,
                "apparentTemperature": 22.77,
                "dewPoint": 19.2,
                "humidity": 0.82,
                "pressure": 1013.82,
                "windSpeed": 5.46,
                "windGust": 5.46,
                "windBearing": 323,
                "cloudCover": 0.24,
                "uvIndex": 0,
                "visibility": 16.093,
                "ozone": 294.5
            },
            {
                "time": 1566097200,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 21.92,
                "apparentTemperature": 22.37,
                "dewPoint": 19.16,
                "humidity": 0.84,
                "pressure": 1013.51,
                "windSpeed": 5.47,
                "windGust": 5.53,
                "windBearing": 310,
                "cloudCover": 0.26,
                "uvIndex": 0,
                "visibility": 16.093,
                "ozone": 295.2
            },
            {
                "time": 1566100800,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 22.02,
                "apparentTemperature": 22.5,
                "dewPoint": 19.37,
                "humidity": 0.85,
                "pressure": 1013.25,
                "windSpeed": 5.55,
                "windGust": 6.65,
                "windBearing": 305,
                "cloudCover": 0.28,
                "uvIndex": 0,
                "visibility": 16.093,
                "ozone": 296
            },
            {
                "time": 1566104400,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 22.23,
                "apparentTemperature": 22.79,
                "dewPoint": 20,
                "humidity": 0.87,
                "pressure": 1013.25,
                "windSpeed": 5.46,
                "windGust": 9.25,
                "windBearing": 298,
                "cloudCover": 0.31,
                "uvIndex": 0,
                "visibility": 16.093,
                "ozone": 297
            },
            {
                "time": 1566108000,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 22.99,
                "apparentTemperature": 23.61,
                "dewPoint": 20.62,
                "humidity": 0.86,
                "pressure": 1013.34,
                "windSpeed": 5.51,
                "windGust": 11.71,
                "windBearing": 311,
                "cloudCover": 0.32,
                "uvIndex": 0,
                "visibility": 16.093,
                "ozone": 297.5
            },
            {
                "time": 1566111600,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 24.58,
                "apparentTemperature": 25.24,
                "dewPoint": 21.36,
                "humidity": 0.82,
                "pressure": 1013.49,
                "windSpeed": 5.51,
                "windGust": 13.73,
                "windBearing": 326,
                "cloudCover": 0.27,
                "uvIndex": 1,
                "visibility": 16.093,
                "ozone": 297.1
            },
            {
                "time": 1566115200,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 26.2,
                "apparentTemperature": 27.94,
                "dewPoint": 22,
                "humidity": 0.78,
                "pressure": 1013.79,
                "windSpeed": 6.38,
                "windGust": 15.61,
                "windBearing": 234,
                "cloudCover": 0.25,
                "uvIndex": 2,
                "visibility": 16.093,
                "ozone": 296.1
            },
            {
                "time": 1566118800,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 27.83,
                "apparentTemperature": 30.5,
                "dewPoint": 22.16,
                "humidity": 0.71,
                "pressure": 1013.85,
                "windSpeed": 8.18,
                "windGust": 17.26,
                "windBearing": 240,
                "cloudCover": 0.19,
                "uvIndex": 4,
                "visibility": 16.093,
                "ozone": 295.9
            },
            {
                "time": 1566122400,
                "summary": "Humid and Partly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 29.18,
                "apparentTemperature": 32.54,
                "dewPoint": 22.41,
                "humidity": 0.67,
                "pressure": 1013.65,
                "windSpeed": 10.11,
                "windGust": 18.85,
                "windBearing": 217,
                "cloudCover": 0.19,
                "uvIndex": 6,
                "visibility": 16.093,
                "ozone": 297.1
            },
            {
                "time": 1566126000,
                "summary": "Humid and Partly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 30.48,
                "apparentTemperature": 34.24,
                "dewPoint": 22.39,
                "humidity": 0.62,
                "pressure": 1013.04,
                "windSpeed": 13.14,
                "windGust": 20.25,
                "windBearing": 189,
                "cloudCover": 0.2,
                "uvIndex": 7,
                "visibility": 16.093,
                "ozone": 298.8
            },
            {
                "time": 1566129600,
                "summary": "Humid and Partly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 31.3,
                "apparentTemperature": 35.21,
                "dewPoint": 22.31,
                "humidity": 0.59,
                "pressure": 1012.68,
                "windSpeed": 15.44,
                "windGust": 20.91,
                "windBearing": 187,
                "cloudCover": 0.28,
                "uvIndex": 7,
                "visibility": 16.093,
                "ozone": 299.5
            },
            {
                "time": 1566133200,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 31.78,
                "apparentTemperature": 35.7,
                "dewPoint": 22.19,
                "humidity": 0.57,
                "pressure": 1012.59,
                "windSpeed": 16.44,
                "windGust": 20.53,
                "windBearing": 191,
                "cloudCover": 0.17,
                "uvIndex": 7,
                "visibility": 16.093,
                "ozone": 298.2
            },
            {
                "time": 1566136800,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 31.5,
                "apparentTemperature": 35.07,
                "dewPoint": 21.88,
                "humidity": 0.57,
                "pressure": 1012.35,
                "windSpeed": 16.4,
                "windGust": 19.49,
                "windBearing": 188,
                "cloudCover": 0.06,
                "uvIndex": 6,
                "visibility": 16.093,
                "ozone": 295.7
            },
            {
                "time": 1566140400,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 30.98,
                "apparentTemperature": 34.34,
                "dewPoint": 21.77,
                "humidity": 0.58,
                "pressure": 1012.09,
                "windSpeed": 15.22,
                "windGust": 18.31,
                "windBearing": 188,
                "cloudCover": 0.08,
                "uvIndex": 4,
                "visibility": 16.093,
                "ozone": 293.8
            },
            {
                "time": 1566144000,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 30.33,
                "apparentTemperature": 33.47,
                "dewPoint": 21.7,
                "humidity": 0.6,
                "pressure": 1011.78,
                "windSpeed": 14.08,
                "windGust": 16.86,
                "windBearing": 188,
                "cloudCover": 0.06,
                "uvIndex": 2,
                "visibility": 16.093,
                "ozone": 292.8
            },
            {
                "time": 1566147600,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 29.52,
                "apparentTemperature": 32.42,
                "dewPoint": 21.65,
                "humidity": 0.63,
                "pressure": 1011.49,
                "windSpeed": 12.14,
                "windGust": 15.2,
                "windBearing": 190,
                "cloudCover": 0.08,
                "uvIndex": 1,
                "visibility": 16.093,
                "ozone": 291.9
            },
            {
                "time": 1566151200,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 28.63,
                "apparentTemperature": 31.26,
                "dewPoint": 21.59,
                "humidity": 0.66,
                "pressure": 1011.65,
                "windSpeed": 9.62,
                "windGust": 13.33,
                "windBearing": 186,
                "cloudCover": 0.09,
                "uvIndex": 0,
                "visibility": 16.093,
                "ozone": 291.9
            },
            {
                "time": 1566154800,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 28.29,
                "apparentTemperature": 30.91,
                "dewPoint": 21.76,
                "humidity": 0.68,
                "pressure": 1012.27,
                "windSpeed": 8.84,
                "windGust": 11.27,
                "windBearing": 157,
                "cloudCover": 0.2,
                "uvIndex": 0,
                "visibility": 16.093,
                "ozone": 292.6
            },
            {
                "time": 1566158400,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 27.18,
                "apparentTemperature": 29.4,
                "dewPoint": 21.83,
                "humidity": 0.73,
                "pressure": 1013.22,
                "windSpeed": 6.53,
                "windGust": 9.44,
                "windBearing": 110,
                "cloudCover": 0.45,
                "uvIndex": 0,
                "visibility": 16.093,
                "ozone": 293.9
            },
            {
                "time": 1566162000,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0.0072,
                "precipProbability": 0.01,
                "precipType": "rain",
                "temperature": 26.27,
                "apparentTemperature": 28,
                "dewPoint": 21.75,
                "humidity": 0.76,
                "pressure": 1014.16,
                "windSpeed": 5.36,
                "windGust": 8.9,
                "windBearing": 48,
                "cloudCover": 0.64,
                "uvIndex": 0,
                "visibility": 16.093,
                "ozone": 294.7
            },
            {
                "time": 1566165600,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 25.8,
                "apparentTemperature": 26.48,
                "dewPoint": 21.73,
                "humidity": 0.78,
                "pressure": 1014.49,
                "windSpeed": 6.04,
                "windGust": 10.17,
                "windBearing": 70,
                "cloudCover": 0.72,
                "uvIndex": 0,
                "visibility": 16.093,
                "ozone": 294.1
            },
            {
                "time": 1566169200,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 25.44,
                "apparentTemperature": 26.11,
                "dewPoint": 21.65,
                "humidity": 0.8,
                "pressure": 1014.8,
                "windSpeed": 7.97,
                "windGust": 12.64,
                "windBearing": 64,
                "cloudCover": 0.74,
                "uvIndex": 0,
                "visibility": 16.093,
                "ozone": 293.2
            },
            {
                "time": 1566172800,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 25.12,
                "apparentTemperature": 25.8,
                "dewPoint": 21.62,
                "humidity": 0.81,
                "pressure": 1014.73,
                "windSpeed": 10.17,
                "windGust": 15.33,
                "windBearing": 56,
                "cloudCover": 0.69,
                "uvIndex": 0,
                "visibility": 16.093,
                "ozone": 292.1
            },
            {
                "time": 1566176400,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 24.8,
                "apparentTemperature": 25.5,
                "dewPoint": 21.64,
                "humidity": 0.83,
                "pressure": 1014.67,
                "windSpeed": 12.55,
                "windGust": 18.39,
                "windBearing": 55,
                "cloudCover": 0.54,
                "uvIndex": 0,
                "visibility": 16.093,
                "ozone": 291.2
            },
            {
                "time": 1566180000,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 24.62,
                "apparentTemperature": 25.32,
                "dewPoint": 21.69,
                "humidity": 0.84,
                "pressure": 1014.89,
                "windSpeed": 15.11,
                "windGust": 21.7,
                "windBearing": 62,
                "cloudCover": 0.33,
                "uvIndex": 0,
                "visibility": 16.093,
                "ozone": 290.3
            },
            {
                "time": 1566183600,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0.0051,
                "precipProbability": 0.01,
                "precipType": "rain",
                "temperature": 24.18,
                "apparentTemperature": 24.9,
                "dewPoint": 21.69,
                "humidity": 0.86,
                "pressure": 1015.37,
                "windSpeed": 16.78,
                "windGust": 23.99,
                "windBearing": 66,
                "cloudCover": 0.17,
                "uvIndex": 0,
                "visibility": 16.093,
                "ozone": 289.6
            },
            {
                "time": 1566187200,
                "summary": "Clear",
                "icon": "clear-night",
                "precipIntensity": 0.0072,
                "precipProbability": 0.01,
                "precipType": "rain",
                "temperature": 23.8,
                "apparentTemperature": 24.5,
                "dewPoint": 21.44,
                "humidity": 0.87,
                "pressure": 1015.61,
                "windSpeed": 16.89,
                "windGust": 24.31,
                "windBearing": 62,
                "cloudCover": 0.11,
                "uvIndex": 0,
                "visibility": 16.093,
                "ozone": 289.4
            },
            {
                "time": 1566190800,
                "summary": "Clear",
                "icon": "clear-night",
                "precipIntensity": 0.0094,
                "precipProbability": 0.01,
                "precipType": "rain",
                "temperature": 23.42,
                "apparentTemperature": 24.11,
                "dewPoint": 21.27,
                "humidity": 0.88,
                "pressure": 1015.89,
                "windSpeed": 16.13,
                "windGust": 23.6,
                "windBearing": 57,
                "cloudCover": 0.1,
                "uvIndex": 0,
                "visibility": 16.093,
                "ozone": 289.5
            },
            {
                "time": 1566194400,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0.0094,
                "precipProbability": 0.01,
                "precipType": "rain",
                "temperature": 23.58,
                "apparentTemperature": 24.24,
                "dewPoint": 21.15,
                "humidity": 0.86,
                "pressure": 1016.19,
                "windSpeed": 15.94,
                "windGust": 23.21,
                "windBearing": 55,
                "cloudCover": 0.09,
                "uvIndex": 0,
                "visibility": 16.093,
                "ozone": 289.6
            },
            {
                "time": 1566198000,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0.0072,
                "precipProbability": 0.01,
                "precipType": "rain",
                "temperature": 24.79,
                "apparentTemperature": 25.42,
                "dewPoint": 21.19,
                "humidity": 0.8,
                "pressure": 1016.4,
                "windSpeed": 16.85,
                "windGust": 23.78,
                "windBearing": 61,
                "cloudCover": 0.05,
                "uvIndex": 1,
                "visibility": 16.093,
                "ozone": 289.5
            },
            {
                "time": 1566201600,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 26.63,
                "apparentTemperature": 28.43,
                "dewPoint": 21.31,
                "humidity": 0.73,
                "pressure": 1016.44,
                "windSpeed": 18.3,
                "windGust": 24.72,
                "windBearing": 73,
                "cloudCover": 0.02,
                "uvIndex": 3,
                "visibility": 16.093,
                "ozone": 289.3
            },
            {
                "time": 1566205200,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 28.21,
                "apparentTemperature": 30.45,
                "dewPoint": 21.11,
                "humidity": 0.65,
                "pressure": 1016.56,
                "windSpeed": 19.82,
                "windGust": 25.63,
                "windBearing": 85,
                "cloudCover": 0,
                "uvIndex": 5,
                "visibility": 16.093,
                "ozone": 289.2
            },
            {
                "time": 1566208800,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 29.26,
                "apparentTemperature": 31.78,
                "dewPoint": 21.16,
                "humidity": 0.62,
                "pressure": 1016.73,
                "windSpeed": 21.62,
                "windGust": 26.61,
                "windBearing": 94,
                "cloudCover": 0,
                "uvIndex": 7,
                "visibility": 16.093,
                "ozone": 289.5
            },
            {
                "time": 1566212400,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 29.72,
                "apparentTemperature": 32.25,
                "dewPoint": 21.06,
                "humidity": 0.6,
                "pressure": 1016.84,
                "windSpeed": 23.53,
                "windGust": 27.55,
                "windBearing": 100,
                "cloudCover": 0,
                "uvIndex": 8,
                "visibility": 16.093,
                "ozone": 289.9
            },
            {
                "time": 1566216000,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 29.73,
                "apparentTemperature": 32.22,
                "dewPoint": 20.97,
                "humidity": 0.59,
                "pressure": 1016.83,
                "windSpeed": 24.55,
                "windGust": 27.89,
                "windBearing": 105,
                "cloudCover": 0,
                "uvIndex": 9,
                "visibility": 16.093,
                "ozone": 290.2
            },
            {
                "time": 1566219600,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 29.51,
                "apparentTemperature": 31.9,
                "dewPoint": 20.9,
                "humidity": 0.6,
                "pressure": 1016.58,
                "windSpeed": 24.04,
                "windGust": 27.17,
                "windBearing": 107,
                "cloudCover": 0,
                "uvIndex": 8,
                "visibility": 16.093,
                "ozone": 290.5
            },
            {
                "time": 1566223200,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 28.93,
                "apparentTemperature": 31.11,
                "dewPoint": 20.74,
                "humidity": 0.61,
                "pressure": 1016.06,
                "windSpeed": 22.63,
                "windGust": 25.81,
                "windBearing": 108,
                "cloudCover": 0,
                "uvIndex": 7,
                "visibility": 16.093,
                "ozone": 290.6
            },
            {
                "time": 1566226800,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 28.37,
                "apparentTemperature": 30.42,
                "dewPoint": 20.68,
                "humidity": 0.63,
                "pressure": 1015.85,
                "windSpeed": 21.15,
                "windGust": 24.54,
                "windBearing": 107,
                "cloudCover": 0,
                "uvIndex": 4,
                "visibility": 16.093,
                "ozone": 290.8
            },
            {
                "time": 1566230400,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 27.87,
                "apparentTemperature": 29.77,
                "dewPoint": 20.6,
                "humidity": 0.65,
                "pressure": 1015.62,
                "windSpeed": 19.72,
                "windGust": 23.37,
                "windBearing": 103,
                "cloudCover": 0,
                "uvIndex": 2,
                "visibility": 16.093,
                "ozone": 291
            },
            {
                "time": 1566234000,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 27.32,
                "apparentTemperature": 29.08,
                "dewPoint": 20.57,
                "humidity": 0.67,
                "pressure": 1015.85,
                "windSpeed": 18.17,
                "windGust": 22.27,
                "windBearing": 97,
                "cloudCover": 0,
                "uvIndex": 1,
                "visibility": 16.093,
                "ozone": 291.3
            },
            {
                "time": 1566237600,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 26.63,
                "apparentTemperature": 28.2,
                "dewPoint": 20.55,
                "humidity": 0.69,
                "pressure": 1015.92,
                "windSpeed": 16.91,
                "windGust": 21.89,
                "windBearing": 91,
                "cloudCover": 0,
                "uvIndex": 0,
                "visibility": 16.093,
                "ozone": 291.5
            }
        ]
    },
    "daily": {
        "summary": "Rain on Tuesday, with high temperatures falling to 27°C on Tuesday.",
        "icon": "rain",
        "data": [
            {
                "time": 1565992800,
                "summary": "Partly cloudy throughout the day.",
                "icon": "partly-cloudy-day",
                "sunriseTime": 1566018208,
                "sunsetTime": 1566067818,
                "moonPhase": 0.57,
                "precipIntensity": 0.0008,
                "precipIntensityMax": 0.0062,
                "precipIntensityMaxTime": 1566000000,
                "precipProbability": 0.01,
                "precipType": "rain",
                "temperatureHigh": 31.08,
                "temperatureHighTime": 1566046800,
                "temperatureLow": 21.92,
                "temperatureLowTime": 1566097200,
                "apparentTemperatureHigh": 34.29,
                "apparentTemperatureHighTime": 1566046800,
                "apparentTemperatureLow": 22.37,
                "apparentTemperatureLowTime": 1566097200,
                "dewPoint": 20.78,
                "humidity": 0.73,
                "pressure": 1015.79,
                "windSpeed": 9.86,
                "windGust": 23.39,
                "windGustTime": 1566050400,
                "windBearing": 215,
                "cloudCover": 0.2,
                "uvIndex": 8,
                "uvIndexTime": 1566039600,
                "visibility": 10.792,
                "ozone": 290.9,
                "temperatureMin": 21.39,
                "temperatureMinTime": 1566014400,
                "temperatureMax": 31.08,
                "temperatureMaxTime": 1566046800,
                "apparentTemperatureMin": 21.97,
                "apparentTemperatureMinTime": 1566014400,
                "apparentTemperatureMax": 34.29,
                "apparentTemperatureMaxTime": 1566046800
            },
            {
                "time": 1566079200,
                "summary": "Humid and partly cloudy throughout the day.",
                "icon": "partly-cloudy-day",
                "sunriseTime": 1566104670,
                "sunsetTime": 1566154131,
                "moonPhase": 0.6,
                "precipIntensity": 0.0016,
                "precipIntensityMax": 0.0072,
                "precipIntensityMaxTime": 1566162000,
                "precipProbability": 0.01,
                "precipType": "rain",
                "temperatureHigh": 31.78,
                "temperatureHighTime": 1566133200,
                "temperatureLow": 23.42,
                "temperatureLowTime": 1566190800,
                "apparentTemperatureHigh": 35.7,
                "apparentTemperatureHighTime": 1566133200,
                "apparentTemperatureLow": 24.11,
                "apparentTemperatureLowTime": 1566190800,
                "dewPoint": 21.14,
                "humidity": 0.73,
                "pressure": 1013.29,
                "windSpeed": 8.65,
                "windGust": 20.91,
                "windGustTime": 1566129600,
                "windBearing": 206,
                "cloudCover": 0.25,
                "uvIndex": 7,
                "uvIndexTime": 1566129600,
                "visibility": 16.093,
                "ozone": 295.2,
                "temperatureMin": 21.92,
                "temperatureMinTime": 1566097200,
                "temperatureMax": 31.78,
                "temperatureMaxTime": 1566133200,
                "apparentTemperatureMin": 22.37,
                "apparentTemperatureMinTime": 1566097200,
                "apparentTemperatureMax": 35.7,
                "apparentTemperatureMaxTime": 1566133200
            },
            {
                "time": 1566165600,
                "summary": "Clear throughout the day.",
                "icon": "clear-day",
                "sunriseTime": 1566191131,
                "sunsetTime": 1566240444,
                "moonPhase": 0.63,
                "precipIntensity": 0.0026,
                "precipIntensityMax": 0.0094,
                "precipIntensityMaxTime": 1566190800,
                "precipProbability": 0.04,
                "precipType": "rain",
                "temperatureHigh": 29.73,
                "temperatureHighTime": 1566216000,
                "temperatureLow": 22.27,
                "temperatureLowTime": 1566270000,
                "apparentTemperatureHigh": 32.25,
                "apparentTemperatureHighTime": 1566212400,
                "apparentTemperatureLow": 22.8,
                "apparentTemperatureLowTime": 1566270000,
                "dewPoint": 21.08,
                "humidity": 0.74,
                "pressure": 1015.96,
                "windSpeed": 17.09,
                "windGust": 27.89,
                "windGustTime": 1566216000,
                "windBearing": 84,
                "cloudCover": 0.14,
                "uvIndex": 9,
                "uvIndexTime": 1566216000,
                "visibility": 16.093,
                "ozone": 290.7,
                "temperatureMin": 23.42,
                "temperatureMinTime": 1566190800,
                "temperatureMax": 29.73,
                "temperatureMaxTime": 1566216000,
                "apparentTemperatureMin": 24.11,
                "apparentTemperatureMinTime": 1566190800,
                "apparentTemperatureMax": 32.25,
                "apparentTemperatureMaxTime": 1566212400
            },
            {
                "time": 1566252000,
                "summary": "Rain in the afternoon and evening.",
                "icon": "rain",
                "sunriseTime": 1566277593,
                "sunsetTime": 1566326755,
                "moonPhase": 0.66,
                "precipIntensity": 0.5178,
                "precipIntensityMax": 2.6966,
                "precipIntensityMaxTime": 1566302400,
                "precipProbability": 0.58,
                "precipType": "rain",
                "temperatureHigh": 26.54,
                "temperatureHighTime": 1566295200,
                "temperatureLow": 19.3,
                "temperatureLowTime": 1566363600,
                "apparentTemperatureHigh": 27.67,
                "apparentTemperatureHighTime": 1566295200,
                "apparentTemperatureLow": 19.62,
                "apparentTemperatureLowTime": 1566363600,
                "dewPoint": 19.33,
                "humidity": 0.76,
                "pressure": 1018.29,
                "windSpeed": 12.35,
                "windGust": 29.55,
                "windGustTime": 1566259200,
                "windBearing": 65,
                "cloudCover": 0.14,
                "uvIndex": 8,
                "uvIndexTime": 1566302400,
                "visibility": 16.093,
                "ozone": 300.5,
                "temperatureMin": 21.25,
                "temperatureMinTime": 1566338400,
                "temperatureMax": 26.54,
                "temperatureMaxTime": 1566295200,
                "apparentTemperatureMin": 21.65,
                "apparentTemperatureMinTime": 1566338400,
                "apparentTemperatureMax": 27.67,
                "apparentTemperatureMaxTime": 1566295200
            },
            {
                "time": 1566338400,
                "summary": "Partly cloudy throughout the day.",
                "icon": "partly-cloudy-day",
                "sunriseTime": 1566364054,
                "sunsetTime": 1566413066,
                "moonPhase": 0.69,
                "precipIntensity": 0.0102,
                "precipIntensityMax": 0.0775,
                "precipIntensityMaxTime": 1566338400,
                "precipProbability": 0.06,
                "precipType": "rain",
                "temperatureHigh": 27.39,
                "temperatureHighTime": 1566396000,
                "temperatureLow": 18.79,
                "temperatureLowTime": 1566450000,
                "apparentTemperatureHigh": 28.03,
                "apparentTemperatureHighTime": 1566396000,
                "apparentTemperatureLow": 19.04,
                "apparentTemperatureLowTime": 1566450000,
                "dewPoint": 17.58,
                "humidity": 0.73,
                "pressure": 1020.43,
                "windSpeed": 7.94,
                "windGust": 19.31,
                "windGustTime": 1566399600,
                "windBearing": 263,
                "cloudCover": 0.43,
                "uvIndex": 7,
                "uvIndexTime": 1566385200,
                "visibility": 16.093,
                "ozone": 302,
                "temperatureMin": 19.3,
                "temperatureMinTime": 1566363600,
                "temperatureMax": 27.39,
                "temperatureMaxTime": 1566396000,
                "apparentTemperatureMin": 19.62,
                "apparentTemperatureMinTime": 1566363600,
                "apparentTemperatureMax": 28.03,
                "apparentTemperatureMaxTime": 1566396000
            },
            {
                "time": 1566424800,
                "summary": "Clear throughout the day.",
                "icon": "clear-day",
                "sunriseTime": 1566450516,
                "sunsetTime": 1566499375,
                "moonPhase": 0.72,
                "precipIntensity": 0.0027,
                "precipIntensityMax": 0.0105,
                "precipIntensityMaxTime": 1566428400,
                "precipProbability": 0.02,
                "precipType": "rain",
                "temperatureHigh": 28.75,
                "temperatureHighTime": 1566482400,
                "temperatureLow": 19.79,
                "temperatureLowTime": 1566536400,
                "apparentTemperatureHigh": 29.45,
                "apparentTemperatureHighTime": 1566482400,
                "apparentTemperatureLow": 19.79,
                "apparentTemperatureLowTime": 1566536400,
                "dewPoint": 17.73,
                "humidity": 0.71,
                "pressure": 1019.64,
                "windSpeed": 9.05,
                "windGust": 15.09,
                "windGustTime": 1566486000,
                "windBearing": 245,
                "cloudCover": 0.1,
                "uvIndex": 8,
                "uvIndexTime": 1566475200,
                "visibility": 16.093,
                "ozone": 307.6,
                "temperatureMin": 18.79,
                "temperatureMinTime": 1566450000,
                "temperatureMax": 28.75,
                "temperatureMaxTime": 1566482400,
                "apparentTemperatureMin": 19.04,
                "apparentTemperatureMinTime": 1566450000,
                "apparentTemperatureMax": 29.45,
                "apparentTemperatureMaxTime": 1566482400
            },
            {
                "time": 1566511200,
                "summary": "Clear throughout the day.",
                "icon": "clear-day",
                "sunriseTime": 1566536977,
                "sunsetTime": 1566585684,
                "moonPhase": 0.75,
                "precipIntensity": 0,
                "precipIntensityMax": 0,
                "precipIntensityMaxTime": 1566579600,
                "precipProbability": 0,
                "temperatureHigh": 28.89,
                "temperatureHighTime": 1566565200,
                "temperatureLow": 19.79,
                "temperatureLowTime": 1566622800,
                "apparentTemperatureHigh": 29.49,
                "apparentTemperatureHighTime": 1566565200,
                "apparentTemperatureLow": 19.87,
                "apparentTemperatureLowTime": 1566622800,
                "dewPoint": 16.22,
                "humidity": 0.62,
                "pressure": 1018.77,
                "windSpeed": 8.95,
                "windGust": 15.15,
                "windGustTime": 1566565200,
                "windBearing": 169,
                "cloudCover": 0,
                "uvIndex": 8,
                "uvIndexTime": 1566561600,
                "visibility": 16.093,
                "ozone": 307,
                "temperatureMin": 19.79,
                "temperatureMinTime": 1566536400,
                "temperatureMax": 28.89,
                "temperatureMaxTime": 1566565200,
                "apparentTemperatureMin": 19.79,
                "apparentTemperatureMinTime": 1566536400,
                "apparentTemperatureMax": 29.49,
                "apparentTemperatureMaxTime": 1566565200
            },
            {
                "time": 1566597600,
                "summary": "Partly cloudy throughout the day.",
                "icon": "partly-cloudy-day",
                "sunriseTime": 1566623438,
                "sunsetTime": 1566671991,
                "moonPhase": 0.79,
                "precipIntensity": 0.002,
                "precipIntensityMax": 0.0105,
                "precipIntensityMaxTime": 1566604800,
                "precipProbability": 0.01,
                "precipType": "rain",
                "temperatureHigh": 29.28,
                "temperatureHighTime": 1566651600,
                "temperatureLow": 22.27,
                "temperatureLowTime": 1566702000,
                "apparentTemperatureHigh": 30.16,
                "apparentTemperatureHighTime": 1566651600,
                "apparentTemperatureLow": 22.44,
                "apparentTemperatureLowTime": 1566712800,
                "dewPoint": 17.18,
                "humidity": 0.64,
                "pressure": 1017.77,
                "windSpeed": 8.08,
                "windGust": 15.41,
                "windGustTime": 1566655200,
                "windBearing": 191,
                "cloudCover": 0.11,
                "uvIndex": 8,
                "uvIndexTime": 1566648000,
                "visibility": 16.093,
                "ozone": 295.3,
                "temperatureMin": 19.79,
                "temperatureMinTime": 1566622800,
                "temperatureMax": 29.28,
                "temperatureMaxTime": 1566651600,
                "apparentTemperatureMin": 19.87,
                "apparentTemperatureMinTime": 1566622800,
                "apparentTemperatureMax": 30.16,
                "apparentTemperatureMaxTime": 1566651600
            }
        ]
    },
    "flags": {
        "sources": [
            "meteoalarm",
            "cmc",
            "gfs",
            "icon",
            "isd",
            "madis"
        ],
        "meteoalarm-license": "Based on data from EUMETNET - MeteoAlarm [https://www.meteoalarm.eu/]. Time delays between this website and the MeteoAlarm website are possible; for the most up to date information about alert levels as published by the participating National Meteorological Services please use the MeteoAlarm website.",
        "nearest-station": 5.987,
        "units": "ca"
    },
    "offset": 2
}

export default sampleData;